### PR TITLE
text_str_2_Uni decodes in utf-8 instead of ascii

### PR DESCRIPTION
**Pull request by h3llrais3r**
will fix a lot of strange characters in the gamedbinfo xml generation.

I'm not sure it this has impact on other things, but I think utf-8 should be used everywhere?

### CODE REVIEW

**Comment by Wintermute0110** [comment]
I need to review this patch further before merging.

**Comment by h3llrais3r** [comment]
Other option is to make the 'encoding' an optional parameter that is default 'ascii'.
If we do it like this, we can still pass 'utf-8'. If nothing is passed, it fallbacks to 'ascii'.
What do you think?

**Comment by Wintermute0110** [comment]
Unicode caused a lot of problems with AEL in the past so before merging this I want to check all the places where the function is calling. Also, the Offline Scraper XMLs must be UTF-8, otherwise is an error in the XML, no in AEL.

**Comment by h3llrais3r** [comment]
That's why I proposed the last change. If I make it a parameter, you can still use 'ascii' in AEL, but use 'utf-8' for the generation of the xml's. Currently it's using 'ascii' for the xml generation from the csv's, which causes  the strange characters.

**Comment by h3llrais3r** [comment]
So I don't need to make it a parameter? You'll be using utf-8 everywhere?

**Comment by Wintermute0110** [comment]
Let's keep it as it is now. If this causes some problems for 0.9.7 I will add the parameter.

**Pull request merged**
