### PR TITLE
Feature/android support

### PR DESCRIPTION
**Pull request by chrisism**
Fixed string formatting by adding indices

### CODE REVIEW

**Comment by Wintermute0110** [comment]
Will merge ASAP. First I have to commit something. By the way, what Kodi version are you running?

**Comment by chrisism** [comment]
I run the latest stable kodi on android, 16.1? or .2. the kids have taken over the TV, can't double check hehe. But yeah if you can give some tips about the best way to import my old AL xml I can check out if everything else works on android and compare.First opinion after running it, you have done a real good job.
ow yeah, did you take quotes in filenames/arguments in account when starting a rom? I had to fix that in the old version of AL. I can double check that myself and send you the fix later on.
Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Wintermute 0110 <notifications@github.com> 
Datum: 04-06-2016  13:39  (GMT+01:00) 
Aan: "Wintermute0110/plugin.program.advanced.emulator.launcher" <plugin.program.advanced.emulator.launcher@noreply.github.com> 
Cc: Christian Jungerius <cwjungerius@gmail.com>, Author <author@noreply.github.com> 
Onderwerp: Re: [Wintermute0110/plugin.program.advanced.emulator.launcher]
  Feature/android support (#2) 

Will merge ASAP. First I have to commit something. By the way, what Kodi version are you running?

**Comment by Wintermute0110** [comment]
Done! Thanks a lot for the Android patch!

Thanks mate, I hope you will enjoy AEL.

Regarding Python version... that's weird... I'm running Kodi 16.1 Jarvis and ships with Python version 2.7.11+ According to your PM in the forum Python version on Android is 2.6.5! Weird weird weird... that may be the cause of the problems. One of the things I updated is the old (A) ('bla bla %s' % string) to the more modern (B) .format(). Eventually Kodi will ship with Python 3 and then (A) will become obsolete. Anyway, I will add indices to {} from now on :)

Regarding importing AL launchers.xml: I have not thought on that... the reason I decided to do AEL was that one month ago one of the AL file corruption destroyed my launchers.xml. When I realised what was happening all the 5 backups were gone as well. That was the straw that broke the camel's back and decided to finish AEL ASAP. Because my old launchers.xml was destroyed I just created new categories/launchers/etc from scratch. Now, scanning of new ROMs is really fast if you use metadata offline scrapping and local images only. I had about 15 launchers with about 10000 ROMs in total and took about 30 minutes to rebuild, including time typing launcher info.

I guess the easiest thing to do is a Python script that reads AL launchers.xml and writes an AEL categories.xml. I have changed a few fields in the data model (and corrected some redundancies in AL data model) and main problem will be the platform, which is very important for the offline scrapers. I think the utility will set all platforms to Unknown in AEL and then you can easily change from the Launcher context menu. Programming the utility will take some time, a 2/3 hours... maybe next weekend will be ready.

Quotes: yes, I take quotes into account. Typical launcher will be: retroarch -L /path/to/core "%rom%". The "" quotes are necessary if the ROM has spaces in its name (most ROMs do with the notable exception of MAME ROMs). If you find a problem with this in your Android box please send a patch.

Lastly, I'm programming the virtual categories Browse by Year, Browse by Genre, etc. This will be the very last feature before release. There's going to be some instability in the plugin for a couple of days.

**Comment by chrisism** [comment]
Yeah, don't know what it is with the python versions. Might be because its android. But the .format way of writing texts is much nicer indeed. Just in general the whole codebase looks much nicer with your work. If I come upon something missing, nice to add or broken with android I'll see if I can help out. 
I saw that rufoo added support for AEL with the last release. Maybe check also with parallex to get AEL as the default for the games link. 

I made a commandline tool myself to sort out my whole roms collection, scrape and build up the launchers xml myself. After that I just copied the launcher xml into AL. Maybe for this I'll add a feature to decompile the launcher xml into seperate NFO files so I can import those with AEL again.
I bet that if you add something to import the old launchers xml you make a lot of people happy and get more on board with the addon. A lot of people already put some much time in getting their current xml correct, it would maybe trigger people more if they know that they can just import it instead of starting all over. Even if the scraper already works so much better.

**Comment by Wintermute0110** [comment]
Thanks for your help. Yeah, I will check with parallex once plugin reaches 1.0.0.

Regarding importing AL launchers.xml: you have a point, lad! Indeed many people spent a lot of time building a nice launchers.xml, which taking into account the limitations of AL was a painful process. Myself did a set of utilities to filter ROMs (get a parent clone list, and filter MAME ROMs to remove "clutter") to keep launchers.xml size to minimum. Have a look at the NARS project in my Github if interested.

Anyway, since I currently have not a proper launchers.xml, would you like to share your's so I can test the importer? I will add an option under "Settings" -- "Advanced" -- 'Import AL launcher.xml' so running AEL for AL users will take just one minute.

Also, I spent quite a lot of time with the scrapers. Previous implementation had a look of duplicate code and some terrible hacks. Now, there is a nice object model with no code redundancy and easy to maintain. AEL scrapers can be run outside Kodi, just need a Python intepreter (look at the scripts in resources/tests/). If you have some nice scrapping code (Mobygames, Giantbomb, etc.) please send a patch.

**Comment by chrisism** [comment]
How do you want to receive it. I added it to this reply. Rename to xml.

[launchers.txt](https://github.com/Wintermute0110/plugin.program.advanced.emulator.launcher/files/300007/launchers.txt)

**Comment by Wintermute0110** [comment]
Thanks! I did a first implementation and seems to work OK with you "nonstandard" launchers.xml. Some notes:

a) I see what you mean about the ' and " quotes. AEL should work OK because it properly quotes XML. AL way of loading/writing XML did not conform to the XML standard so hence the problems. If you find any issue with this comment if here or open a bug report in Github.

b) I have discovered some problems with the utf-8 encoding. Your plots/description have some utf-8 characters. I did a couple of workarounds so the imported works. However, the ROM Information Viewer fails when the ROM has utf-8 in the description.

Tomorrow I will try to fix b) and other things (virtual launchers must not be editable, for example).

**Comment by Wintermute0110** [comment]
Forgot to say: platform is set to Unknown for all launchers. Change it by editing the launcher. Having a correct platform is only meaningless for the scrapers.

**Comment by chrisism** [comment]
Yeah, I combined some AL output with a different seperate scraper output and then put in stuff using my own tool. Might be a bit mixed up, but I got all the details I wanted shown in AL in Kodi so I was happy with it. But I didnt notice any problems with the UTF8 encoding before or is it just in your addon? UTF8 is a default encoding you see a lot in XML.
This is the xml that I have up till now. I just started to buildy my collection up again since I saw the sexy cirrus mods. I still have some rom collections waiting and I'll probably do those with your addon right away.

I'll get your latests version on my kodi this evening to try out. And I'll see if I can help out with the other scrapers. I got most of my contents from emumovies. Although its behind a login and there is a cap on the amount of content to download per day for free users, it might be a nice source also. But I'll check the sites you commented first.

**Comment by Wintermute0110** [comment]
It wasn't your fault, it was AEL's fault. I was not using Unicode internally. I'm currently doing a batch of changes to solve that and other small fixes here and there. In the last days I added quite a lot of new stuff but was not careful about Unicode handling.

Looking forward to your comments!

**Comment by Wintermute0110** [comment]
I pushed a big commit with lot of things (and maybe introduced some new bugs...). I already talked with paradix and maybe ROMs will be stored as JSON instead of XML. Virtual launchers (Browse by Title, etc.) now are stored as JSON, where ROMs are stored as XML. That will allow us to compare. Please have a try and tell me what you think. Import your ROMs, play with AEL, but do not make important changes in AEL cos maybe you will need to reimport in the future.

**Comment by chrisism** [comment]
The import works perfect. Got everything there now.
Maybe only add a toaster message or other feedback in the beginning. It took a moment before I saw a 'working' message, didnt know if it was actually doing something before that.
Other small thing is that it imported/added a new 'Emulators' category from the xml. Now I have the initial AEL category and my old AL category both named 'Emulators'. Small detail because I can just as well remove the category and go further with the imported one. Maybe add a note on your readme doc/topic start that this will be the behavior. Don't think you need to fix something for this, it is already a nice bonus feature as it works now.

Man, you really did a great job with the speed. It works perfect and a good loading experience. Using JSON will ofcourse help with some overhead you have with the xml elements, as in filesize. Dont know if it also helps with loading times, but current state is already great.
No obvious bugs found yet

**Comment by Wintermute0110** [comment]
Cool it works OK.

I already changed all ROM storage to JSON. I was doing some tests in my Kodi box yesterday. For a 6000 ROM launcher XML took about 8 seconds to load. Same launcher in JSON was less than 2 seconds. For launchers of 1500 ROMs XML takes some 1/2 seconds but JSON loads almost instantly. Paradix was right and the decision was obvious. I already changed all ROM storage to JSON (including Favourites) in a patch I will commit soon. You will need to delete all stuff in the plugin data directory and import again. I think there will be no more data-model changes, but do not do any serious edition (spend lot of time changing metadata, for example) in AEL until 1.0.0 is released.

About the double Emulators category: yeah, that's a side effect of Angelscry <default> category. You changed the name from <default> to Emulators, but ID is still default. The importer creates a new random ID for the default category, so by total chance in your case you end with two Emulators categories. If you do the importing again, you will end with a third Emulators category, two empty Emulators category and all launchers moved to the new category, and so on! Yes, I will make a note about this behavior in the Wiki.

Also, added a notification when importing ROMs :)

Speed: AL had some terrible hacks that made it really slow when you had more than about 1000 ROMs in total. On top of that, storing everything into one launchers.xml was a bad design decision, although it had some programmingwise advantages. Just cleaning the design and sorting out that improved speed A LOT (although as I said in Rufoo's thread, reworking AL took quite a while, much longer than I anticipated). Now, with the JSON storage I think plugin is as fast as it can be!

**Pull request merged**
